spring.application.name=koi-ia-service

spring.datasource.url=jdbc:mysql://localhost:3306/despescar_koiia
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:despescar_dev}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8088

koi.catalog.package-service-url=http://localhost:8086
koi.catalog.flight-service-url=http://localhost:8081
koi.catalog.hotel-service-url=http://localhost:8083
koi.catalogo.connect-timeout-ms=2000
koi.catalogo.read-timeout-ms=5000

# --- CONSIGUE LA API KEY DE GROK ATRAVÉS DE ESTA PÁGINA https://console.groq.com/home
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.chat.options.temperature=0.2

springdoc.swagger-ui.path=/swagger-ui.html